DO $$
BEGIN
  CREATE TYPE "MacroProfile" AS ENUM ('BALANCED', 'HIGH_PROTEIN', 'LOW_CARB', 'HIGH_CARB');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "UserProfile"
ADD COLUMN IF NOT EXISTS "macroProfile" "MacroProfile" NOT NULL DEFAULT 'BALANCED';
