CREATE TYPE "TargetFormula" AS ENUM (
  'MIFFLIN_ST_JEOR',
  'HARRIS_BENEDICT_ORIGINAL',
  'HARRIS_BENEDICT_REVISED',
  'OWEN'
);

ALTER TABLE "UserProfile"
ADD COLUMN "targetFormula" "TargetFormula" NOT NULL DEFAULT 'MIFFLIN_ST_JEOR';
